name: Test Template

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        framework: [ 'net10.0' ]
        package: [ 'Hosting.OpenGauss', "Hosting.DMDB" ]

    name: Test (${{ matrix.package }} / ${{ matrix.framework }})

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.framework == 'net8.0' && '8.0.x' || matrix.framework == 'net9.0' && '9.0.x' || '10.0.x' }}
          include-prerelease: true

      - name: Install Aspire SDK
        run: |
          curl -sSL https://aspire.dev/install.sh | bash
          echo "export PATH=\"$HOME/.dotnet/tools:$PATH\"" >> $GITHUB_ENV

      - name: Validation of Aspire SDK
        run: |
          export PATH="$HOME/.dotnet/tools:$PATH"
          aspire --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release -f ${{ matrix.framework }} ${{ format('tests/NetCorePal.Aspire.{0}.Tests/NetCorePal.Aspire.{0}.Tests.csproj', matrix.package) }} --no-restore

      - name: Test
        run: dotnet test -c Release -f ${{ matrix.framework }} ${{ format('tests/NetCorePal.Aspire.{0}.Tests/NetCorePal.Aspire.{0}.Tests.csproj', matrix.package) }} --no-build --verbosity normal --logger "console;verbosity=detailed"
